[2025-10-11 14:04:55,328] 
        Error in [/var/folders/yp/3qncdc4d7q7cmvdhg6dt4x040000gn/T/ipykernel_2487/848079753.py] at line number [20] : division by zero 
 Traceback : Traceback (most recent call last):
  File "/var/folders/yp/3qncdc4d7q7cmvdhg6dt4x040000gn/T/ipykernel_2487/848079753.py", line 20, in <module>
    a = 1 / 0
ZeroDivisionError: division by zero

