[2025-10-11 14:13:18,390] 
        Error in [/Users/hophukhang/document_portal/exception/custom_exception.py] at line number [22] : division by zero 
 Traceback : Traceback (most recent call last):
  File "/Users/hophukhang/document_portal/exception/custom_exception.py", line 22, in <module>
    a = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero

